### ISSUE TITLE
Cronjobs run in / instead of /app

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#1124] opened 2019-06-17 13:26 UTC
**Describe the bug**
Cronjobs defined as `drush cron` don't necessarily run in the /app directory.

This can break sites that use composer installed drush versions as in / there is not the same drush version loaded as inside /app

**To Reproduce**
1. create cronjob that runs a `pwd`
2. check cronjob output

**Expected behavior**
Cronjob runs in /app

**Additional context**
This issue can be circumvented by defining the cronjobs with the `--root` argument: `drush --root=/app/ cron`

Those issue has been brought up by @twerthmueller earlier and the workaround was tested sucessfully.

**Comment by dasrecht** [comment] 2019-07-08 09:11
running `cd /app` within the cronjob will only lead to additional issues e.g.

```2019-07-08T09:06:28Z CRONJOB: cd /app && wp cron event run --due-now --url=example.com
Agent pid 21
Identity added: /home/.ssh/key (/home/.ssh/key)
/lagoon/entrypoints.sh: exec: line 15: cd: not found
End of log

**Comment by Schnitzel** [comment] 2020-10-13 14:30
we had another customer that had an issue with this: the drush8 launcher was unable to realize that there is a drush10 installed in the vendor folder and all crons where started as drush8 instead of drush10 creating a lot of issues

**Comment by fjgarlin** [comment] 2021-02-03 09:13
Had the same problem as well on a project and the solution is the `--root` argument for now.

**Comment by fjgarlin** [comment] 2021-02-03 10:32
Is there a plan to roll out a fix for this? We've scanned our projects and have +50 using `drush cron` without the root parametre.

**Comment by tobybellwood** [comment] 2021-02-04 23:56
ok - on discovery, let's look at finding why the cronjobs don't respect the WORKDIR settings.  There's _all sorts_ of drush 8/9/10 inter-relation issues that would be more easily solved by running from the correct directory!

**Comment by smlx** [comment] 2021-02-05 05:27
Could the fix for this issue just be documentation?

**Comment by smlx** [comment] 2021-02-05 06:31
There's some logic here for finding the drush root, could it be tweaked to fall back on `/app` if running in Lagoon?
https://github.com/amazeeio/lagoon/blob/master/services/drush-alias/web/aliases.drushrc.php.stub#L39-L53

This is linked from https://github.com/amazeeio/lagoon/issues/485, which this issue appears to be a duplicate of.

**Comment by tobybellwood** [comment] 2021-02-05 07:40
(one of) the issues here is that you can't pass a `root` to rush launcher - which is the element that intercepts the drush call.  Outside of an actual root, it hunts around for an install.  It defaults to the drush 8 installed globally, but it then gets tangled when it comes across drush9/10 isms inside the /app/web folders.

The drush launcher itself never checks the drush config (drushrc.php, or drush.yml) to see what the defined root is.  Running any drush inside `/app` has the desired effect, it's just hitting it from `/` that causes confusion.

I'm still trying to work out how/where/when the cronjob workdir gets set, or has changed...

**Comment by smlx** [comment] 2021-02-05 09:59
It is set here: https://github.com/webdevops/go-crond/blob/master/main.go#L438-L442

The main problem in this issue seems to be the disconnect between `drush cron`, which drupal developers expect to just work, and actual unix cron, where the rule has always been to either `cd ... && command`, or use absolute paths.

BTW @dasrecht `cd /app && ...` works here, I'm not sure why it broke for you?

Could we solve this by documenting that cronjobs run in `/` and you need `cd /app && ...` if you want something different?

**Comment by Schnitzel** [comment] 2021-02-05 13:38
oh wow nice find @smlx
we always tried to find the issue in the entrypoints or in kubernetes, but not that actually `go-crond` would change the directory...

so the problem is that depending on how often the cronjob runs it runs in another enviornments:
- less often than 15min it runs in a Kubernetes `CronJob` object which runs the cronjob defined in `WORKDIR` of the Dockerfile
- more often than 15min it runs inside the cli container which uses `go-crond` and as we learned it runs in `/` always

I would very much like to run all cronjobs always in `WORKDIR` as this makes the most sense:
- if you ssh into the container you land in workdir
- if you run any command in the Dockerfile it's running in workdir
- local developers also connect to the container in workdir

so I think for me it would be the best if we can somehow make sure that the cronjob command runs in workdir without needing to explain the customers that they have to do a `cd /app` themselves.

**Closed as completed** 2021-02-19 23:29 UTC
