### ISSUE TITLE
Identify orphaned services when a deployment is executed

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#3494] opened 2023-07-28 02:48 UTC
At present, if you were to delete or rename a service in your `docker-compose.yml` file, then Lagoon will not remove this in Kubernetes when you do a deployment.

This can lead to running additional pods in the cluster, to which do not necessarily belong there.

A recent cluster I audited, it was 3% of all Lagoon application pods running.

Unsure what the ideal solution here is, I think perhaps in the first instance, if we can "pass" a deployment with warnings, this could be one of the warnings.

Alternatively, if there was a way for the end user to force the removal of orphaned services upon deploy I think that would also be a good idea.

**Comment by shreddedbacon** [comment] 2023-07-28 02:52
Thought there was already an issue for this somewhere, but can't seem to find it.

**Comment by rocketeerbkw** [comment] 2023-07-29 01:03
Duplicate of https://github.com/uselagoon/build-deploy-tool/issues/146

**Closed as not planned by rocketeerbkw** 2023-07-29 01:03 UTC
Labels: enhancement, 2-build-deploy
