### ISSUE TITLE
deleting a project does not remove it from groups

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#3004] opened 2022-01-26 18:03 UTC
When a project is deleted, performing a query against the API like

```
groupByName(name: "example){
  projects{
    id
    name
  }
}
```
will return a null result in the set. The project ID is also still present in the group in Keycloak.

**Comment by rocketeerbkw** [comment] 2022-01-26 20:45
Duplicate of #1562

**Closed as completed by rocketeerbkw** 2022-01-26 20:45 UTC
