### ISSUE TITLE
Lagoon API for Environment Variables should allow upsert (insert or update)

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#2556] opened 2021-03-05 08:50 UTC
The current API for environment variables is sub-optimal, if you are looking to ensure a variable matches a particular value.

## Current process

1. Get the value (for comparison)
2. If the value exists, and is wrong, delete it
3. Insert the new value

This is a rather long process to do, to just set an environment variable.

## Compounding factors

There is a large customer in region that synchronises a lot of environment variables, to ensure they are consistent with a configuration database that they maintain. The process takes around 30 minutes to run end to end.

Not only is this slow, the Lagoon API also experiences more load than is actually necessary.

## Ideal solution

The environment variable add function should insert or update the value, and hide this detail from the end user.

## Why this should not go in Lagoon CLI only

The Lagoon CLI project attempts to keep API parity with Lagoon, so features like this should be upstreamed to Lagoon, so all users benefit from it.

**Comment by tobybellwood** [comment] 2021-03-05 08:56
duplicate of https://github.com/amazeeio/lagoon/issues/1677

There is currently more work on how to manage variables (esp deleted ones) over at https://github.com/amazeeio/lagoon/pull/2348 - we will evaluate whether there is a solution for this here.

**Closed as completed** 2022-11-03 00:13 UTC
Labels: 1-api-auth
