### ISSUE TITLE
Cronjobs running in the cli container have no concurrency protection

### ISSUE THREAD

**Issue by nicksantamaria** [uselagoon/lagoon#2399] opened 2020-12-14 02:47 UTC
# Describe the bug

The native `CronJob` objects created by Lagoon have `.spec.ConcurrencyPolicy: Forbid` set. This prevents cronjobs overlapping with each other if the execution time is longer than the period between each schedule.

When cronjobs are executed in the cli container (I believe this happens if their schedule is less than every 15 minutes?) this same protection is not present.

## To Reproduce

Add a per-minute cronjob which writes the timestamp to a file, sleeps for 2 minutes, and writes the date to the file again.

```
      - name: Test concurrency
        schedule: "*/1 * * * *"
        command: 'EXECUTION_TIME=$(date) && echo $EXECUTION_TIME >> docroot/sites/default/files/test.txt && sleep 120 && echo $EXECUTION_TIME >> docroot/sites/default/files/test.txt'
        service: cli
```

This ends up creating a file like so, with the timestamps alternating.

```
Mon 14 Dec 2020 13:43:42 AEDT
Mon 14 Dec 2020 13:44:36 AEDT
Mon 14 Dec 2020 13:43:42 AEDT
Mon 14 Dec 2020 13:44:36 AEDT
```

## Expected behavior

The times should appear in pairs, in order.

```
Mon 14 Dec 2020 13:43:42 AEDT
Mon 14 Dec 2020 13:43:42 AEDT
Mon 14 Dec 2020 13:45:36 AEDT
Mon 14 Dec 2020 13:45:36 AEDT
```

## Additional context

We discovered this issue when a cronjob that wasn't thread safe resulted in duplicate emails being sent.

**Comment by Schnitzel** [comment] 2020-12-14 02:54
Lagoon uses https://github.com/christophlehmann/go-crond to run cronjobs inside the containers and like all other cronjob implementation of Unix there is no concurrency protection, see also https://unix.stackexchange.com/questions/58481/can-a-crontab-job-run-concurrently-with-itself

So I think that's not an issue? It's correct that we have cronjobs that are created via CronJob Object with `.spec.ConcurrencyPolicy: Forbid` created, mostly because we had some customers that had cronjobs that took multiple hours and they where started every 30min, ending up in hundreds of pods running which in the end destroyed the clusters. 
If a customer does the same inside the cli pod we don't so much care, as the cli pod itself has a memory limit and therefore protects the cluster from using too many resources.
I'm aware that this is two different implementations of cronjobs, but the reason we have concurrency protection on the CronJob Objects is not a feature but rather a protection of the platform.

**Comment by nicksantamaria** [comment] 2020-12-14 03:50
You make fair points. Perhaps the way to deal with this is document the difference in behavior [here](https://lagoon.readthedocs.io/en/latest/using_lagoon/lagoon_yml/#cron-jobs-environmentsnamecronjobs).

**Comment by smlx** [comment] 2020-12-14 05:23
We should also probably document the standard workaround, something like this (untested):

```
      - name: Test concurrency
        schedule: "*/1 * * * *"
        command: 'flock -n /tmp/flock.test -c "EXECUTION_TIME=\$(date) && echo \$EXECUTION_TIME >> docroot/sites/default/files/test.txt && sleep 120 && echo \$EXECUTION_TIME >> docroot/sites/default/files/test.txt"'
        service: cli
```

**Comment by rocketeerbkw** [comment] 2022-07-07 21:39
Duplicate of https://github.com/uselagoon/lagoon-images/issues/172

**Closed as not planned by rocketeerbkw** 2022-07-07 21:39 UTC
