### ISSUE TITLE
The Remote Shell documentation refers to rsh but rsh is not required

### ISSUE THREAD

**Issue by bryangruneberg** [uselagoon/lagoon#1366] opened 2019-11-01 22:10 UTC
**Describe the bug**
The Lagoon docs refer to rsh for access containers. It appears that 'rsh' should no longer be appended to the ssh command.

**To Reproduce**
Steps to reproduce the behavior, run the following:
```ssh -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 32222 -t some-project-master@ssh.lagoon.amazeeio.cloud rsh whoami
sh: rsh: not found
command terminated with exit code 127
Connection to ssh.lagoon.amazeeio.cloud closed.```

**Comment by twardnw** [comment] 2019-11-01 22:13
Duplicate of #1275 , handled in #1277

**Closed as completed by twardnw** 2019-11-01 22:13 UTC
