### ISSUE TITLE
Dark mode doesn't work on Delete popup

### ISSUE THREAD

**Issue by PeterSalsa** [uselagoon/lagoon#3459] opened 2023-06-06 23:00 UTC
# Describe the bug

When Dark mode/styling is enabled and you press the Delete button on an environment, the confirmation popup isn't in dark mode and is therefore difficult to read.

## To Reproduce

Steps to reproduce the behaviour:

1. Enable Dark mode
1. Go to a project's environment
2. Click on Delete
3. Note light styling in confirmation popup

## Expected behaviour

The confirmation popup should be styled in dark mode when enabled.

## Screenshots

![image](https://github.com/uselagoon/lagoon/assets/126627037/51bab28a-546b-4dcb-bcc2-8ee8a3aa1a91)

![image](https://github.com/uselagoon/lagoon/assets/126627037/9589052e-261f-4f80-b46a-0745ac2c67c6)

## Additional context

Using Lagoon v2.15.0

**Comment by shreddedbacon** [comment] 2023-06-06 23:01
Duplicate of https://github.com/uselagoon/lagoon-ui/issues/129

**Closed as completed by shreddedbacon** 2023-06-06 23:01 UTC

**Comment by PeterSalsa** [comment] 2023-06-06 23:25
Ah, didn't realise there was a separate repo, sorry.
