### ISSUE TITLE
Race condition during database restore

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#2454] opened 2021-01-14 06:13 UTC
# Describe the bug

https://github.com/amazeeio/lagoon/pull/2149 split the default `mysqldump` backup into two stages to facilitate selectively ignoring the data of particular tables (in this case, `watchdog`).

This widens the window of time between `CREATE` and `INSERT` during restore, which also widens the window for something else to write to the table after the `CREATE`, but before the `INSERT`.

Best practice is to stop any other service talking to the database during restore. However that isn't always easy to do so we should make our `mysqldump` as robust as possible. Therefore IMO we should revert the change made in https://github.com/amazeeio/lagoon/pull/2149, and instead educate users to disable `watchdog` on Lagoon. Special-casing a single table always felt a bit hacky anyway.

Anyone have thoughts on this?

## To Reproduce

1. Restore a backup file using e.g. `drush sqlc` while Drupal is still connected to the database.
2. Occasionally see an error like this:

```
drush sqlc < backup-example.mariadb.sql
> ERROR 1062 (23000) at line 8573: Duplicate entry 'entity_type' for key 'PRIMARY'
```

## Expected behavior

It would be great to make the window of possible race condition as small as possible.

## Screenshots

n/a

## Additional context

Best practice for DB restore is to stop any other services connecting to the database during restore. This will completely avoid the race condition.

As the above is not always practical, just retrying the restore will probably work since the chance of hitting the race condition is likely quite small.

**Comment by ivangrynenko** [comment] 2021-01-14 22:02
@smlx 
Few notes to your comments:
1. The watchdog is always disabled in the affected services.
2. The exact line and character position will always be the same when the MySQL import is reinstated and database cleaned (drush sql-drop).
3. Database is emptied before attempting a restoration (drush sql-drop).

I suspect the problem is happening during mysqldump, when a data is getting written into non-locked tables (no write lock). The affected tables were cache* in all instances where we saw this error, which makes sense as Drupal does rebuild some caches from time to time.

**Comment by smlx** [comment] 2021-01-15 02:42
> 1. The watchdog is always disabled in the affected services.

not for all Lagoon users ;-)

> I suspect the problem is happening during mysqldump, when a data is getting written into non-locked tables (no write lock).

I don't think that is the problem because [we use](https://github.com/amazeeio/lagoon/blob/master/images/oc-build-deploy-dind/openshift-templates/mariadb-dbaas/prebackuppod.yml#L66) `--single-transaction`. I also inspected the dump which caused the error you saw, and it was valid.

> The affected tables were cache* in all instances where we saw this error, which makes sense as Drupal does rebuild some caches from time to time.

Yes, this is the race condition during restore:

1. Restore does `CREATE TABLE ...`
2. Drupal writes to the table.
3. Restore locks the table and does `INSERT`.
4. Error occurs.

The only way to avoid this completely is to disconnect/scale-down Drupal during restore.

Another option is to just retry the restore - you might get lucky and win the race.

**Comment by tobybellwood** [comment] 2024-02-22 21:58
Not seen additional issues raised from this, closing for now?

Additionally, active/standby would work to divert prod traffic whilst you do open-heart database surgery

**Closed as completed by tobybellwood** 2024-02-22 21:58 UTC
Labels: 8-automation-helpers
