### ISSUE TITLE
lagoon UI - scalability problem with deployments list

### ISSUE THREAD

**Issue by jordotech** [uselagoon/lagoon#2174] opened 2020-08-24 17:05 UTC
Hello, we have reached 250 deployments for our dev branch and the lagoon UI is taking ~1min to load the list of deployments.  As time goes on it will continue to get slower until the page is unusable.

Solution- add pagination to the list of deployments

https://ui-lagoon-master.ch.amazee.io/projects/ipsum-front/ipsum-front-dev/deployments

**Comment by seanhamlin** [comment] 2020-08-24 20:00
Duplicate of #2158

**Closed as completed by seanhamlin** 2020-08-24 20:00 UTC
