### ISSUE TITLE
Export projects' used storage and database size

### ISSUE THREAD

**Issue by eskp** [uselagoon/lagoon#754] opened 2018-11-14 05:43 UTC
This is more of a start of a discussion issue for exposing used storage by a project/namespace and project's database size. This has came up during the need of monthly report creation for customer billing.
Right now the process is fairly manual of extracting project storage from GraphQL and database size from Mysql (via Openshift).
One idea is for Lagoon to write this data periodically to Elasticsearch and/or export these metrics on an endpoint in Prometheus format (this can be done by instrumenting Lagoon with a client library https://prometheus.io/docs/instrumenting/clientlibs/).
The data will then be available historically and can be queried with Grafana, making a nice looking dashboards.

**Comment by tobybellwood** [comment] 2022-11-10 20:20
duplicate of  #602

**Closed as completed by tobybellwood** 2022-11-10 20:20 UTC
Labels: 4-metrics-alerting
