### ISSUE TITLE
Random Keycloak errors

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#1337] opened 2019-10-23 20:54 UTC
ever since we switched to RBAC with Keycloak we seem to have weird errors from the Keycloak API whenever the Lagoon API talks to it. Usually running the same GraphQL Request right after it usually solves the error, but this causes all kind of issues (Lagoon CI failures, failed builds, etc.)

Request:
```
query project {
  projectByName (name: "foobar") {
    id
    name
    privateKey
    openshift {
      id
      name
    }
    groups {
      id
      name
      members {
        role
        user {
          id
          lastName
          firstName
          sshKeys {
            id
            name
            keyValue
            keyFingerprint
          }
        }
      }
    }
  }
}
```

errors:
```
  "errors": [
    {
      "message": "Group not found: 189e43c1-4ecb-4a88-99ab-37c094955ebe",
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ],
      "path": [
        "projectByName",
        "groups"
      ]
    }
  ],
  "data": {
    "projectByName": {
      "id": 52,
      "groups": null
    }
  }
}
```

```
{
  "errors": [
    {
      "message": "Request failed with status code 404",
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ],
      "path": [
        "projectByName",
        "groups"
      ]
    }
  ],
  "data": {
    "projectByName": {
      "id": 52,
      "groups": null
    }
  }
}
```

```
{
  "errors": [
    {
      "message": "Cannot read property 'map' of null",
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ],
      "path": [
        "projectByName",
        "groups"
      ]
    }
  ],
  "data": {
    "projectByName": {
      "id": 52,
      "groups": null
    }
  }
}
```

We experienced these issues while building the gitlab sync and solved it with easy retries:
https://github.com/amazeeio/lagoon/blob/master/services/api/src/gitlab-sync/groups.ts#L57-L63

Of course it would be really good to actually find the reason for these issues and solve them, but maybe in the current state as a hotfix the best would be to just implement a retry handler whenever we talk to the keycloak API?

**Comment by vincenzodnp** [comment] 2019-11-06 11:50
Today another weird behaviour.
This query works:
```
query userbyssh {
  userBySshKey (sshKey: "ssh-rsa xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx") {
    id
    email
    groups {
      id
      name
      members {
        role
        user {
          id
          lastName
          firstName
        }
      }
    }
  }
}
```
while this one not: `Request failed with status code 404`
```
query singleProject {
  projectByName(name: "drupal-example") {
    name
    groups {
      name
      id
    }
  }
}
```
It seems like there is correlation between queries that join `groups` and `projects` compared for example with queries joining `groups` and `users`

**Comment by smlx** [comment] 2020-01-29 06:20
Just realised this is a duplicate of #1294

**Closed as completed** 2022-11-10 20:39 UTC
Labels: bug, priority-high
