### ISSUE TITLE
Per project custom backup schedules in .lagoon.yml

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#2679] opened 2021-05-26 16:47 UTC
Similar to the pattern for custom backup retention, let us also allow custom backup schedules to be defined

**Comment by cdchris12** [comment] 2021-05-26 17:23
In addition to simply allowing custom backup schedule definitions, we should put some common senes guardrails in place. 

As k8up only supports tracking backups down to the hour, it wouldn't make sense for us to allow backups to happen more frequently than one per hour, for instance.

**Comment by seanhamlin** [comment] 2021-06-15 00:56
Initialled closed this as a duplicate of https://github.com/amazeeio/lagoon/issues/2303, but I think they are 2 different issues now, this one https://github.com/amazeeio/lagoon/issues/2679 is about per project settings in `.lagoon.yml`, and https://github.com/amazeeio/lagoon/issues/2303 is about a cluster level setting.

**Closed as completed** 2021-07-02 20:15 UTC
Labels: 8-automation-helpers, lagoon.yml
