### ISSUE TITLE
bytes_read is stored as string in logs-db

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#701] opened 2018-10-23 05:25 UTC
To allow for doing calculations on the number of bytes per request, bytes_read should be stored as a number instead of a string in the logs-db elasticsearch.

**Comment by Schnitzel** [comment] 2018-10-25 05:15
duplicate of https://github.com/amazeeio/lagoon/issues/674 closing

**Closed as completed by Schnitzel** 2018-10-25 05:15 UTC
